knpu_oauth2_client:
  # can be set to the service id of a service that implements Guzzle\ClientInterface
  # http_client: null

  # options to configure the default http client
  # http_client_options:
  #     timeout: 0
  #     # if you want to disable the proxy (e.g. local GitLab OAuth) - set it to "false"
  #     proxy: null
  #     Use only with proxy option set
  #     verify: false

  clients:
    # will create service: "knpu.oauth2.client.auth0"
    # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\Auth0Client
    # composer require riskio/oauth2-auth0
    auth0:
      # must be "auth0" - it activates that type!
      type: auth0
      # add and set these environment variables in your .env files
      client_id: '%env(OAUTH_AUTH0_CLIENT_ID)%'
      client_secret: '%env(OAUTH_AUTH0_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: connect_auth0_check
      redirect_params: {}
      # Your custom/definite Auth0 domain, e.g. "login.mycompany.com". Set this if you use Auth0's Custom Domain feature. The "account" and "region" parameters will be ignored in this case.
      # custom_domain: null
      # Your Auth0 domain/account, e.g. "mycompany" if your domain is "mycompany.auth0.com"
      account: dev-fpstjn2pxxcscocr.us
      # Your Auth0 region, e.g. "eu" if your tenant is in the EU.
      region: us
      # whether to check OAuth2 "state": defaults to true
      # use_state: true